[pytest]
pythonpath = .
testpaths =
    categorical_boolean_extractor/tests
    e2e_pipeline/tests
    input_orchestrator/tests
    lustre_architecture_generator/tests
    preference_extractor/tests
    preference_extractor/tests_layer2
    preference_extractor/tests_weighting
    requirement_state/tests
